"""All user-facing Spanish text, centralized.

Per AGENTS.md §3 / DESIGN.md §5.4, this is the ONLY place UI strings live.
Never inline a user-facing literal inside a view file — reference a key here
so the English/Spanish boundary stays unambiguous.
"""

from __future__ import annotations

APP_TITLE = "Caja Chica"

APP_SUBTITLE = "Registro de ventas, stock, gastos y caja"

USER_PICKER_TITLE = "Quién está trabajando ahora?"
USER_PICKER_PROMPT = "Selecciona tu nombre para continuar"
USER_PICKER_NO_USERS = "Aún no hay usuarios registrados."
USER_PICKER_CREATE_LABEL = "Crear un nuevo usuario"
USER_PICKER_CREATE_HINT = "Nombre del usuario nuevo"
USER_PICKER_CREATE_BUTTON = "Crear"
USER_PICKER_SELECT_BUTTON = "Seleccionar"
USER_REQUIRED_ERROR = "Escribe un nombre antes de crear el usuario."

MAIN_WELCOME = "Bienvenido"
BALANCE_LABEL = "Disponible total"
BALANCE_CASH_LABEL = "Efectivo"
BALANCE_QR_LABEL = "QR"
CURRENT_USER_LABEL = "Usuario actual"

# --- Shared / navigation shell ---------------------------------------------

NAV_TITLE = "Menú"
NAV_VENTAS = "Ventas"
NAV_CATALOGO = "Catálogo"
NAV_RESTOCK = "Reponer stock"
NAV_GASTOS = "Gastos"
NAV_FIADO = "Fiado"
NAV_ARQUEO = "Arqueo"

COMMON_CANCEL = "Cancelar"
COMMON_CONFIRM = "Confirmar"
COMMON_SAVE = "Guardar"
COMMON_CLOSE = "Cerrar"

# --- Sales screen -----------------------------------------------------------

SALES_TITLE = "Registrar venta"
SALES_PRODUCT_LABEL = "Producto"
SALES_QUANTITY_LABEL = "Cantidad"
SALES_ADD_BUTTON = "Agregar al carrito"
SALES_CART_TITLE = "Carrito"
SALES_CART_EMPTY = "El carrito está vacío."
SALES_RUNNING_TOTAL = "Total"
SALES_CASH_LABEL = "Pago en efectivo"
SALES_QR_LABEL = "Pago en QR"
SALES_CREDIT_LABEL = "Venta a crédito (fiado)"
SALES_REMAINING = "Falta $ {remaining} por cubrir."
SALES_OVERPAID = "El pago supera el total en $ {diff}."
SALES_CUSTOMER_NAME_LABEL = "Nombre del cliente"
SALES_CUSTOMER_NOTE_LABEL = "Nota (opcional)"
SALES_SUBMIT_BUTTON = "Registrar venta"
SALES_EDIT_MODE = "Editando venta #{logical_id} — al guardar se crea una nueva versión"
SALES_CANCEL_EDIT = "Cancelar edición"
SALES_EDIT_LINE_BUTTON = "Cambiar precio de esta línea"
SALES_OVERRIDE_TITLE = "Cambiar precio de línea"
SALES_OVERRIDE_HINT = "Precio unitario para esta línea"
SALES_REMOVE_LINE_BUTTON = "Quitar línea"
SALES_OVERRIDE_BADGE = "Precio modificado"
SALES_RECENT_TITLE = "Ventas de hoy"
SALES_EMPTY_RECENT = "Aún no hay ventas hoy."
SALES_EDIT_BUTTON = "Editar"
SALES_VOID_BUTTON = "Anular"
SALES_EDIT_LOCKED_TOOLTIP = "No se puede editar: la venta a crédito ya tiene pagos registrados."
SALES_VOID_LOCKED_TOOLTIP = "No se puede anular: la venta a crédito ya tiene pagos registrados."
SALES_EDITING_WITH_BALANCE = ""
SALES_VOID_TITLE = "¿Anular esta venta?"
SALES_VOID_QUESTION = "La venta dejará de contar en el saldo y el stock volverá."
SALES_VOID_CONFIRM = "Sí, anular"
SALES_TOTAL_LABEL = "Total: $ {total}"
SALES_METHODS_CREDIT = "Fiado ({customer})"
SALES_EMPTY_CART_ERROR = "Agrega al menos un producto al carrito."
SALES_NEED_CUSTOMER_NAME = "Escribe el nombre del cliente para la venta a crédito."
SALES_NO_PAYMENT_ERROR = "Registra un pago para esta venta."
SALES_PAYMENT_MISMATCH = "Los pagos suman $ {paid}, pero la venta suma $ {total}."
SALES_INVALID_AMOUNT = "Revisa los montos (números y punto decimal para centavos)."
SALES_INVALID_QUANTITY = "Escribe una cantidad válida (entero mayor a cero)."
SALES_NEED_PRODUCT = "Selecciona un producto para agregar."
SALES_SUCCESS_CREATED = "Venta registrada."
SALES_SUCCESS_EDITED = "Venta actualizada (nueva versión creada)."
SALES_SUCCESS_VOIDED = "Venta anulada."
SALES_WRITE_ERROR = "No se pudo guardar la venta: {message}"
SALES_NO_ACTIVE_PRODUCTS = "No hay productos activos. Crea uno en Catálogo."
SALES_CANNOT_EDIT_COLLECTED = "Esta venta a crédito ya tiene pagos registrados y no puede modificarse ni anularse."

# --- Catalog screen ---------------------------------------------------------

CATALOG_TITLE = "Catálogo"
CATALOG_SUBTITLE = "Productos y precios"
CATALOG_CREATE_TITLE = "Nuevo producto"
CATALOG_NAME_LABEL = "Nombre"
CATALOG_PRICE_LABEL = "Precio"
CATALOG_CREATE_BUTTON = "Crear producto"
CATALOG_INVALID_PRICE = "Escribe un precio válido (mayor o igual a cero)."
CATALOG_EMPTY_NAME = "Escribe un nombre para el producto."
CATALOG_SHOW_INACTIVE = "Mostrar inactivos"
CATALOG_CHANGE_PRICE_BUTTON = "Cambiar precio"
CATALOG_NEW_PRICE_LABEL = "Nuevo precio"
CATALOG_PREVIOUS_PRICE = "Precio anterior: $ {price}"
CATALOG_REASON_LABEL = "Motivo (opcional)"
CATALOG_SAVE_PRICE_BUTTON = "Guardar precio"
CATALOG_DEACTIVATE_TOOLTIP = "Desactivar (quita del selector de ventas)"
CATALOG_REACTIVATE_TOOLTIP = "Reactivar"
CATALOG_INACTIVE_BADGE = "Inactivo"
CATALOG_NO_PRODUCTS = "No hay productos todavía."
CATALOG_PRICE_NEVER_SET = "Sin precio"
CATALOG_STOCK_LABEL = "Stock"
CATALOG_SUCCESS_CREATED = "Producto creado."
CATALOG_SUCCESS_PRICE = "Precio actualizado."
CATALOG_WRITE_ERROR = "No se pudo guardar: {message}"

# --- Restock screen ---------------------------------------------------------

RESTOCK_TITLE = "Reponer stock"
RESTOCK_PRODUCT_LABEL = "Producto"
RESTOCK_QUANTITY_LABEL = "Cantidad"
RESTOCK_ADD_BUTTON = "Agregar línea"
RESTOCK_ITEMS_TITLE = "Líneas"
RESTOCK_EMPTY_ITEMS = "Agrega al menos un producto."
RESTOCK_EXPENSE_CASH_LABEL = "Gasto en efectivo (opcional)"
RESTOCK_EXPENSE_QR_LABEL = "Gasto por QR (opcional)"
RESTOCK_EXPENSE_DESC_LABEL = "Descripción del gasto (opcional)"
RESTOCK_PAYMENT_HINT = "El gasto puede pagarse en efectivo y/o QR; cada parte se descuenta del método correspondiente."
RESTOCK_SUBMIT_BUTTON = "Registrar reposición"
RESTOCK_RECENT_TITLE = "Reposiciones recientes"
RESTOCK_EMPTY_RECENT = "No hay reposiciones registradas."
RESTOCK_INVALID_QUANTITY = "Escribe una cantidad válida (entero mayor a cero)."
RESTOCK_NEED_PRODUCT = "Selecciona un producto para agregar."
RESTOCK_INVALID_EXPENSE = "El gasto debe ser mayor a cero si se escribe."
RESTOCK_NO_EXPENSE = "Sin gasto vinculado"
RESTOCK_LINKED_EXPENSE = "Gasto: {description} — $ {amount}"
RESTOCK_EXPENSE_DELETED = "Gasto vinculado (eliminado)"
RESTOCK_SUCCESS = "Reposición registrada."
RESTOCK_WRITE_ERROR = "No se pudo registrar la reposición: {message}"

# --- Expenses screen --------------------------------------------------------

EXPENSES_TITLE = "Gastos"
EXPENSES_CREATE_TITLE = "Nuevo gasto"
EXPENSES_DESCRIPTION_LABEL = "Descripción"
EXPENSES_CASH_LABEL = "Efectivo"
EXPENSES_QR_LABEL = "QR"
EXPENSES_CASH_QR_HINT = "Pago en efectivo y/o QR (la suma se descuenta de cada método)."
EXPENSES_NO_PAYMENT = "Escribe al menos un pago (efectivo o QR)."
EXPENSES_CREATE_BUTTON = "Registrar gasto"
EXPENSES_RECENT_TITLE = "Gastos"
EXPENSES_EMPTY_LIST = "Sin gastos registrados."
EXPENSES_EDIT_MODE = "Editando gasto #{logical_id} — al guardar se crea una nueva versión"
EXPENSES_EDIT_BUTTON = "Editar"
EXPENSES_VOID_BUTTON = "Anular"
EXPENSES_EMPTY_DESC = "Escribe una descripción."
EXPENSES_INVALID_AMOUNT = "Escribe un monto válido mayor a cero."
EXPENSES_BADGE_LINKED = "Vinculado a reposición"
EXPENSES_VOID_TITLE = "¿Anular este gasto?"
EXPENSES_VOID_WARNING = "El gasto dejará de contar en el saldo."
EXPENSES_VOID_BATCH_WARNING = "Este gasto está vinculado a una reposición: el stock de esa reposición NO se modifica."
EXPENSES_VOID_CONFIRM = "Sí, anular"
EXPENSES_SUCCESS_CREATED = "Gasto registrado."
EXPENSES_SUCCESS_EDITED = "Gasto actualizado (nueva versión creada)."
EXPENSES_SUCCESS_VOIDED = "Gasto anulado."
EXPENSES_WRITE_ERROR = "No se pudo guardar el gasto: {message}"

# --- Debts screen -----------------------------------------------------------

DEBTS_TITLE = "Fiado (deudas)"
DEBTS_OPEN_TITLE = "Deudas abiertas"
DEBTS_EMPTY_OPEN = "No hay deudas abiertas."
DEBTS_COL_CUSTOMER = "Cliente"
DEBTS_COL_NOTE = "Nota"
DEBTS_COL_TOTAL = "Total"
DEBTS_COL_PAID = "Pagado"
DEBTS_COL_OUTSTANDING = "Pendiente"
DEBTS_MARK_PAID = "Marcar pagado"
DEBTS_ABONO_LINK = "Abono parcial"
DEBTS_ABONO_LABEL = "Monto del abono"
DEBTS_ABONO_BUTTON = "Registrar abono"
DEBTS_SHOW_SETTLED = "Mostrar saldadas"
DEBTS_SETTLED_TITLE = "Deudas saldadas"
DEBTS_EMPTY_SETTLED = "No hay deudas saldadas."
DEBTS_INVALID_ABONO = "Escribe un monto válido mayor a cero."
DEBTS_ABONO_TOO_LARGE = "El abono no puede superar el saldo pendiente ($ {outstanding})."
DEBTS_SUCCESS_PAID = "Deuda marcada como pagada."
DEBTS_SUCCESS_ABONO = "Abono registrado."
DEBTS_WRITE_ERROR = "No se pudo registrar el pago: {message}"

# --- Cash count (arqueo) screen ---------------------------------------------

ARQUEO_TITLE = "Arqueo de caja"
ARQUEO_COUNTED_LABEL = "Efectivo contado"
ARQUEO_NOTE_LABEL = "Nota (opcional)"
ARQUEO_RECORD_BUTTON = "Registrar arqueo"
ARQUEO_RESULT_TITLE = "Resultado"
ARQUEO_RESULT_MATCH = "La caja cuadra: contaste $ {counted} y se esperaban $ {expected}."
ARQUEO_RESULT_OVER = "Sobran $ {diff} (contaste $ {counted}, se esperaban $ {expected})."
ARQUEO_RESULT_SHORT = "Faltan $ {diff} (contaste $ {counted}, se esperaban $ {expected})."
ARQUEO_HISTORY_TITLE = "Historial de arqueos"
ARQUEO_EMPTY_HISTORY = "No hay arqueos registrados."
ARQUEO_INVALID_AMOUNT = "Escribe una cantidad válida (mayor o igual a cero)."
ARQUEO_WRITE_ERROR = "No se pudo registrar el arqueo: {message}"
ARQUEO_DIFF_LABEL = "Diferencia"
ARQUEO_COUNTED_COL = "Contado"
ARQUEO_EXPECTED_COL = "Esperado"
ARQUEO_DATE_COL = "Fecha"
ARQUEO_USER_COL = "Usuario"
ARQUEO_NOTE_COL = "Nota"
