"""All user-facing Spanish text, centralized.

Per AGENTS.md §3 / DESIGN.md §5.4, this is the ONLY place UI strings live.
Never inline a user-facing literal inside a view file — reference a key here
so the English/Spanish boundary stays unambiguous.
"""

from __future__ import annotations

APP_TITLE = "Caja Chica"

APP_SUBTITLE = "Registro de ventas, stock, gastos y caja"

USER_PICKER_TITLE = "Quién está trabajando ahora?"
USER_PICKER_PROMPT = "Selecciona tu nombre para continuar"
USER_PICKER_NO_USERS = "Aún no hay usuarios registrados."
USER_PICKER_CREATE_LABEL = "Crear un nuevo usuario"
USER_PICKER_CREATE_HINT = "Nombre del usuario nuevo"
USER_PICKER_CREATE_BUTTON = "Crear"
USER_PICKER_SELECT_BUTTON = "Seleccionar"
USER_REQUIRED_ERROR = "Escribe un nombre antes de crear el usuario."

MAIN_WELCOME = "Bienvenido"
BALANCE_LABEL = "Disponible total"
BALANCE_CASH_LABEL = "Efectivo"
BALANCE_QR_LABEL = "QR"
CURRENT_USER_LABEL = "Usuario actual"

# --- Shared / navigation shell ---------------------------------------------

NAV_TITLE = "Menú"
NAV_VENTAS = "Ventas"
NAV_CATALOGO = "Catálogo"
NAV_RESTOCK = "Reponer stock"
NAV_GASTOS = "Gastos"
NAV_FIADO = "Fiado"
NAV_ARQUEO = "Arqueo"

COMMON_CANCEL = "Cancelar"
COMMON_CONFIRM = "Confirmar"
COMMON_SAVE = "Guardar"
COMMON_CLOSE = "Cerrar"

# --- Sales screen -----------------------------------------------------------

SALES_TITLE = "Registrar venta"
SALES_PRODUCT_LABEL = "Producto"
SALES_QUANTITY_LABEL = "Cantidad"
SALES_ADD_BUTTON = "Agregar al carrito"
SALES_CART_TITLE = "Carrito"
SALES_CART_EMPTY = "El carrito está vacío."
SALES_RUNNING_TOTAL = "Total"
SALES_CASH_LABEL = "Pago en efectivo"
SALES_QR_LABEL = "Pago en QR"
SALES_CREDIT_LABEL = "Venta a crédito (fiado)"
SALES_REMAINING = "Falta $ {remaining} por cubrir."
SALES_OVERPAID = "El pago supera el total en $ {diff}."
SALES_CUSTOMER_NAME_LABEL = "Nombre del cliente"
SALES_CUSTOMER_NOTE_LABEL = "Nota (opcional)"
SALES_SUBMIT_BUTTON = "Registrar venta"
SALES_EDIT_MODE = "Editando venta #{logical_id} — al guardar se crea una nueva versión"
SALES_CANCEL_EDIT = "Cancelar edición"
SALES_EDIT_LINE_BUTTON = "Cambiar precio de esta línea"
SALES_OVERRIDE_TITLE = "Cambiar precio de línea"
SALES_OVERRIDE_HINT = "Precio unitario para esta línea"
SALES_REMOVE_LINE_BUTTON = "Quitar línea"
SALES_OVERRIDE_BADGE = "Precio modificado"
SALES_RECENT_TITLE = "Ventas de hoy"
SALES_EMPTY_RECENT = "Aún no hay ventas hoy."
SALES_EDIT_BUTTON = "Editar"
SALES_VOID_BUTTON = "Anular"
SALES_EDIT_LOCKED_TOOLTIP = "No se puede editar: la venta a crédito ya tiene pagos registrados."
SALES_VOID_LOCKED_TOOLTIP = "No se puede anular: la venta a crédito ya tiene pagos registrados."
SALES_EDITING_WITH_BALANCE = ""
SALES_VOID_TITLE = "¿Anular esta venta?"
SALES_VOID_QUESTION = "La venta dejará de contar en el saldo y el stock volverá."
SALES_VOID_CONFIRM = "Sí, anular"
SALES_TOTAL_LABEL = "Total: $ {total}"
SALES_METHODS_CREDIT = "Fiado ({customer})"
SALES_EMPTY_CART_ERROR = "Agrega al menos un producto al carrito."
SALES_NEED_CUSTOMER_NAME = "Escribe el nombre del cliente para la venta a crédito."
SALES_NO_PAYMENT_ERROR = "Registra un pago para esta venta."
SALES_PAYMENT_MISMATCH = "Los pagos suman $ {paid}, pero la venta suma $ {total}."
SALES_INVALID_AMOUNT = "Revisa los montos (números y punto decimal para centavos)."
SALES_INVALID_QUANTITY = "Escribe una cantidad válida (entero mayor a cero)."
SALES_NEED_PRODUCT = "Selecciona un producto para agregar."
SALES_SUCCESS_CREATED = "Venta registrada."
SALES_SUCCESS_EDITED = "Venta actualizada (nueva versión creada)."
SALES_SUCCESS_VOIDED = "Venta anulada."
SALES_WRITE_ERROR = "No se pudo guardar la venta: {message}"
SALES_NO_ACTIVE_PRODUCTS = "No hay productos activos. Crea uno en Catálogo."
SALES_CANNOT_EDIT_COLLECTED = "Esta venta a crédito ya tiene pagos registrados y no puede modificarse ni anularse."

# --- Catalog screen ---------------------------------------------------------

CATALOG_TITLE = "Catálogo"
CATALOG_SUBTITLE = "Productos y precios"
CATALOG_CREATE_TITLE = "Nuevo producto"
CATALOG_NAME_LABEL = "Nombre"
CATALOG_PRICE_LABEL = "Precio"
CATALOG_CREATE_BUTTON = "Crear producto"
CATALOG_INVALID_PRICE = "Escribe un precio válido (mayor o igual a cero)."
CATALOG_EMPTY_NAME = "Escribe un nombre para el producto."
CATALOG_SHOW_INACTIVE = "Mostrar inactivos"
CATALOG_CHANGE_PRICE_BUTTON = "Cambiar precio"
CATALOG_NEW_PRICE_LABEL = "Nuevo precio"
CATALOG_PREVIOUS_PRICE = "Precio anterior: $ {price}"
CATALOG_REASON_LABEL = "Motivo (opcional)"
CATALOG_SAVE_PRICE_BUTTON = "Guardar precio"
CATALOG_DEACTIVATE_TOOLTIP = "Desactivar (quita del selector de ventas)"
CATALOG_REACTIVATE_TOOLTIP = "Reactivar"
CATALOG_INACTIVE_BADGE = "Inactivo"
CATALOG_NO_PRODUCTS = "No hay productos todavía."
CATALOG_PRICE_NEVER_SET = "Sin precio"
CATALOG_STOCK_LABEL = "Stock"
CATALOG_SUCCESS_CREATED = "Producto creado."
CATALOG_SUCCESS_PRICE = "Precio actualizado."
CATALOG_WRITE_ERROR = "No se pudo guardar: {message}"

# --- Restock screen ---------------------------------------------------------

RESTOCK_TITLE = "Reponer stock"
RESTOCK_PRODUCT_LABEL = "Producto"
RESTOCK_QUANTITY_LABEL = "Cantidad"
RESTOCK_ADD_BUTTON = "Agregar línea"
RESTOCK_ITEMS_TITLE = "Líneas"
RESTOCK_EMPTY_ITEMS = "Agrega al menos un producto."
RESTOCK_EXPENSE_CASH_LABEL = "Gasto en efectivo (opcional)"
RESTOCK_EXPENSE_QR_LABEL = "Gasto por QR (opcional)"
RESTOCK_EXPENSE_DESC_LABEL = "Descripción del gasto (opcional)"
RESTOCK_PAYMENT_HINT = "El gasto puede pagarse en efectivo y/o QR; cada parte se descuenta del método correspondiente."
RESTOCK_SUBMIT_BUTTON = "Registrar reposición"
RESTOCK_RECENT_TITLE = "Reposiciones recientes"
RESTOCK_EMPTY_RECENT = "No hay reposiciones registradas."
RESTOCK_INVALID_QUANTITY = "Escribe una cantidad válida (entero mayor a cero)."
RESTOCK_NEED_PRODUCT = "Selecciona un producto para agregar."
RESTOCK_INVALID_EXPENSE = "El gasto debe ser mayor a cero si se escribe."
RESTOCK_NO_EXPENSE = "Sin gasto vinculado"
RESTOCK_LINKED_EXPENSE = "Gasto: {description} — {breakdown}"
RESTOCK_EXPENSE_DELETED = "Gasto vinculado (eliminado)"
RESTOCK_SUCCESS = "Reposición registrada."
RESTOCK_WRITE_ERROR = "No se pudo registrar la reposición: {message}"

# --- Expenses screen --------------------------------------------------------

EXPENSES_TITLE = "Gastos"
EXPENSES_CREATE_TITLE = "Nuevo gasto"
EXPENSES_DESCRIPTION_LABEL = "Descripción"
EXPENSES_CASH_LABEL = "Efectivo"
EXPENSES_QR_LABEL = "QR"
EXPENSES_CASH_QR_HINT = "Pago en efectivo y/o QR (la suma se descuenta de cada método)."
EXPENSES_NO_PAYMENT = "Escribe al menos un pago (efectivo o QR)."
EXPENSES_CREATE_BUTTON = "Registrar gasto"
EXPENSES_RECENT_TITLE = "Gastos"
EXPENSES_EMPTY_LIST = "Sin gastos registrados."
EXPENSES_EDIT_MODE = "Editando gasto #{logical_id} — al guardar se crea una nueva versión"
EXPENSES_EDIT_BUTTON = "Editar"
EXPENSES_VOID_BUTTON = "Anular"
EXPENSES_EMPTY_DESC = "Escribe una descripción."
EXPENSES_INVALID_AMOUNT = "Escribe un monto válido mayor a cero."
EXPENSES_BADGE_LINKED = "Vinculado a reposición"
EXPENSES_VOID_TITLE = "¿Anular este gasto?"
EXPENSES_VOID_WARNING = "El gasto dejará de contar en el saldo."
EXPENSES_VOID_BATCH_WARNING = "Este gasto está vinculado a una reposición: el stock de esa reposición NO se modifica."
EXPENSES_VOID_CONFIRM = "Sí, anular"
EXPENSES_SUCCESS_CREATED = "Gasto registrado."
EXPENSES_SUCCESS_EDITED = "Gasto actualizado (nueva versión creada)."
EXPENSES_SUCCESS_VOIDED = "Gasto anulado."
EXPENSES_WRITE_ERROR = "No se pudo guardar el gasto: {message}"

# --- Debts screen -----------------------------------------------------------

DEBTS_TITLE = "Fiado (deudas)"
DEBTS_OPEN_TITLE = "Deudas abiertas"
DEBTS_EMPTY_OPEN = "No hay deudas abiertas."
DEBTS_COL_CUSTOMER = "Cliente"
DEBTS_COL_NOTE = "Nota"
DEBTS_COL_TOTAL = "Total"
DEBTS_COL_PAID = "Pagado"
DEBTS_COL_OUTSTANDING = "Pendiente"
DEBTS_MARK_PAID = "Marcar pagado"
DEBTS_ABONO_LINK = "Abono parcial"
DEBTS_ABONO_LABEL = "Monto del abono"
DEBTS_ABONO_BUTTON = "Registrar abono"
DEBTS_SHOW_SETTLED = "Mostrar saldadas"
DEBTS_SETTLED_TITLE = "Deudas saldadas"
DEBTS_EMPTY_SETTLED = "No hay deudas saldadas."
DEBTS_INVALID_ABONO = "Escribe un monto válido mayor a cero."
DEBTS_ABONO_TOO_LARGE = "El abono no puede superar el saldo pendiente ($ {outstanding})."
DEBTS_SUCCESS_PAID = "Deuda marcada como pagada."
DEBTS_SUCCESS_ABONO = "Abono registrado."
DEBTS_WRITE_ERROR = "No se pudo registrar el pago: {message}"

# --- Cash count (arqueo) screen ---------------------------------------------

ARQUEO_TITLE = "Arqueo de caja"
ARQUEO_COUNTED_LABEL = "Efectivo contado"
ARQUEO_NOTE_LABEL = "Nota (opcional)"
ARQUEO_RECORD_BUTTON = "Registrar arqueo"
ARQUEO_RESULT_TITLE = "Resultado"
ARQUEO_RESULT_MATCH = "La caja cuadra: contaste $ {counted} y se esperaban $ {expected}."
ARQUEO_RESULT_OVER = "Sobran $ {diff} (contaste $ {counted}, se esperaban $ {expected})."
ARQUEO_RESULT_SHORT = "Faltan $ {diff} (contaste $ {counted}, se esperaban $ {expected})."
ARQUEO_HISTORY_TITLE = "Historial de arqueos"
ARQUEO_EMPTY_HISTORY = "No hay arqueos registrados."
ARQUEO_INVALID_AMOUNT = "Escribe una cantidad válida (mayor o igual a cero)."
ARQUEO_WRITE_ERROR = "No se pudo registrar el arqueo: {message}"
ARQUEO_DIFF_LABEL = "Diferencia"
ARQUEO_COUNTED_COL = "Contado"
ARQUEO_EXPECTED_COL = "Esperado"
ARQUEO_DATE_COL = "Fecha"
ARQUEO_USER_COL = "Usuario"
ARQUEO_NOTE_COL = "Nota"

# --- Excel export screen -----------------------------------------------------

NAV_EXPORT = "Exportar"
EXPORT_TITLE = "Exportar a Excel"
EXPORT_SUBTITLE = "Elegí el rango de fechas y guardá el archivo."
EXPORT_DATE_FROM_LABEL = "Desde (dd/mm/aaaa)"
EXPORT_DATE_TO_LABEL = "Hasta (dd/mm/aaaa)"
EXPORT_BUTTON = "Exportar"
EXPORT_INVALID_DATE = (
    "Escribí las fechas como dd/mm/aaaa (p. ej. 10/09/2026 o 10/09/26), "
    "con /, -, . o espacios."
)
EXPORT_RANGE_ERROR = "La fecha 'desde' no puede ser posterior a 'hasta'."
EXPORT_SUCCESS = "Exportación guardada: {path}"
EXPORT_ERROR = "No se pudo exportar: {message}"
EXPORT_FILE_NAME = "export_{date_from}_{date_to}.xlsx"

# Workbook sheet names / column headers (user-facing, centralised here too).
EXPORT_SHEET_SALES = "Ventas"
EXPORT_SHEET_EXPENSES = "Gastos"
EXPORT_SHEET_DEBTS = "Deudas"
EXPORT_SHEET_BALANCE = "Resumen saldo"
EXPORT_SHEET_AUDIT = "Auditoría"
AUDIT_COL_CATEGORY = "Categoría"
AUDIT_COL_CHANGE_TYPE = "Tipo de cambio"
AUDIT_COL_SUMMARY = "Detalle"
EXPORT_COL_DATE = "Fecha"
EXPORT_COL_PRODUCT = "Producto"
EXPORT_COL_QUANTITY = "Cantidad"
EXPORT_COL_UNIT_PRICE = "Precio unitario"
EXPORT_COL_LINE_TOTAL = "Total línea"
EXPORT_COL_CASH = "Efectivo"
EXPORT_COL_QR = "QR"
EXPORT_COL_CREDIT = "Crédito"
EXPORT_COL_CUSTOMER = "Cliente"
EXPORT_COL_NOTE = "Nota"
EXPORT_COL_DESCRIPTION = "Descripción"
EXPORT_COL_USER = "Usuario"
EXPORT_COL_TOTAL = "Total"
EXPORT_COL_PAID = "Pagado"
EXPORT_COL_OUTSTANDING = "Pendiente"
EXPORT_COL_STATUS = "Estado"
EXPORT_COL_LINKED_RESTOCK = "Vinculado a reposición"
EXPORT_YES = "Sí"
EXPORT_NO = "No"
EXPORT_STATUS_OPEN = "Abierta"
EXPORT_STATUS_SETTLED = "Saldada"
EXPORT_BALANCE_CASH_SALES = "Ventas en efectivo"
EXPORT_BALANCE_QR_SALES = "Ventas por QR"
EXPORT_BALANCE_DEBTS_COLLECTED = "Cobros de fiado"
EXPORT_BALANCE_CASH_EXPENSES = "Gastos en efectivo"
EXPORT_BALANCE_QR_EXPENSES = "Gastos por QR"
EXPORT_BALANCE_NET = "Saldo neto disponible"

# --- Audit trail screen (plan-05) -------------------------------------------

NAV_AUDITORIA = "Auditoría"
AUDIT_TITLE = "Auditoría de cambios"
AUDIT_SUBTITLE = "Quién hizo qué y cuándo — sin posibilidad de borrar el historial."
AUDIT_FILTER_TIME = "Tiempo"
AUDIT_TIME_1H = "Última hora"
AUDIT_TIME_24H = "Últimas 24 horas"
AUDIT_TIME_7D = "Últimos 7 días"
AUDIT_TIME_30D = "Últimos 30 días"
AUDIT_TIME_ALL = "Todo"
AUDIT_FILTER_USER = "Usuario"
AUDIT_FILTER_ALL_USERS = "Todos"
AUDIT_FILTER_CATEGORY = "Categoría"
AUDIT_FILTER_ALL_CATEGORIES = "Todas"
AUDIT_FILTER_CHANGE_TYPE = "Tipo de cambio"
AUDIT_FILTER_ALL_TYPES = "Todos"
AUDIT_TYPE_REGISTRO = "Registro"
AUDIT_TYPE_EDICION = "Edición"
AUDIT_TYPE_ELIMINACION = "Eliminación"
AUDIT_METHOD_CASH = "efectivo"
AUDIT_METHOD_QR = "QR"
AUDIT_METHOD_CREDIT = "fiado"
AUDIT_METHODS_JOIN = " + "
AUDIT_RESULTS_COUNT = "{count} cambios encontrados"
AUDIT_EMPTY = "No hay cambios para los filtros seleccionados."
AUDIT_LOAD_MORE = "Cargar más"
AUDIT_EXPORT_BUTTON = "Exportar esta vista"
AUDIT_EXPORT_FILE_NAME = "auditoria_{date}.xlsx"

# Summary templates (plan-05 Task 2.3) — business facts only, never
# implementation details like logical_id / version / superseded_at.
AUDIT_VENTAS_REGISTRO = "Venta registrada por {user} — ${amount} ({methods})"
AUDIT_VENTAS_EDICION = "Venta editada por {user} — ${amount}"
AUDIT_VENTAS_ELIMINACION = "Venta anulada por {user} — ${amount}"
AUDIT_CATALOGO_REGISTRO = "Producto '{name}' creado por {user} — ${price}"
AUDIT_CATALOGO_EDICION = "Precio de '{name}' editado por {user}: ${old} → ${new}"
AUDIT_RESTOCK_REGISTRO = "Reposición por {user} — {items}"
AUDIT_GASTOS_REGISTRO = "Gasto '{description}' registrado por {user} — ${amount}"
AUDIT_GASTOS_EDICION = "Gasto '{description}' editado por {user} — ${amount}"
AUDIT_GASTOS_ELIMINACION = "Gasto '{description}' anulado por {user}"
AUDIT_FIADO_REGISTRO = "Abono de ${amount} recibido de '{customer}' por {user}"
AUDIT_ARQUEO_REGISTRO = "Arqueo por {user} — contado ${counted}, esperado ${expected}, diferencia ${diff}"

# Expandable detail (plan-05 Task 4) — before/after comparisons.
AUDIT_DETAIL_BUTTON = "Ver detalle"
AUDIT_DETAIL_HIDE = "Ocultar detalle"
AUDIT_DETAIL_VOIDED_PREFIX = "Antes de anular:"
AUDIT_DETAIL_DESCRIPTION = "Descripción: '{description}'"
AUDIT_DETAIL_FIELD = "{field}: {before} → {after}"
AUDIT_DETAIL_TOTAL = "Total: $ {amount}"
AUDIT_DETAIL_ITEMS = "Productos: {items}"
AUDIT_DETAIL_PAYMENT_LABEL = "Pago"

# --- Backup / archive menu actions -------------------------------------------

MENU_ACTIONS = "Acciones"
MENU_BACKUP = "Copiar respaldo"
MENU_ARCHIVE = "Archivar y empezar un nuevo libro"
BACKUP_SUCCESS = "Respaldo guardado: {path}"
BACKUP_ERROR = "No se pudo crear el respaldo: {message}"
ARCHIVE_TITLE = "¿Archivar y empezar un nuevo libro?"
ARCHIVE_QUESTION = "Se creará un nuevo libro vacío y la app seguirá trabajando con él. El libro actual queda intacto en su carpeta."
ARCHIVE_CONFIRM = "Sí, archivar"
ARCHIVE_SUCCESS = "Nuevo libro creado: {path}"
ARCHIVE_ERROR = "No se pudo archivar: {message}"

# --- Archived ledger viewer (read-only) --------------------------------------

MENU_OPEN_ARCHIVE = "Abrir ledger archivado…"
MENU_CLOSE_ARCHIVE = "Cerrar ledger archivado"
ARCHIVE_READ_ONLY_LABEL = "SOLO LECTURA"
ARCHIVE_BANNER_SUFFIX = "— ledger archivado"
ARCHIVE_OPEN_ERROR = "No se pudo abrir el ledger archivado: {message}"
ARCHIVE_TOO_NEW_ERROR = (
    "Este archivo pertenece a una versión más nueva de la app y no puede abrirse."
)
ARCHIVE_CLOSED = "Ledger archivado cerrado."
